### PR TITLE
fixes cooldown flashing

### LINKED ISSUE #1514: Cooldown flashing on detailed idle screen faster than on regular screen
It's not a real bug, more like an inconsistency.

**To Reproduce**

1. Activate **`Cooldown flashing`**.
2. Activate **`Detailed idle screen`**.
3. Heat up the device to **~60°C**.
4. Stop heating.
5. *Memorize* the **rate** at which the temperature reading flashes.
6. Deactivate **`Detailed idle screen`**.
7. Repeat 3. - 4.
8. Note that the flash-**rate** is now much *higher*.

**Expected behavior**
The flash-rate should be the same in any case.

**Details of your device:**
iron  |  Firmware Version
-|-
**TS80P**|**https://github.com/Ralim/IronOS/tree/3e2da605ab9ee3807bcde0921aca760cbddf8d7b**

**Additional info**
I did try to find the corresponding part of code, but did not succeed. 😅

### PR DESCRIPTION
**Pull request by discip**
resolves #1514

### CODE REVIEW

File: source/Core/Threads/OperatingModes/HomeScreen.cpp [hunk 1]
```diff
@@ -164,10 +164,11 @@ void drawHomeScreen(bool buttonLockout) {
         gui_drawBatteryIcon();
       }
       tipDisconnectedDisplay = false;
-      if (tipTemp > 55)
+      if (tipTemp > 55) {
```
Comment (Ralim) [inline source/Core/Threads/OperatingModes/HomeScreen.cpp:167]: This causes the blink to kick in and out randomly, the 10C gap here is deliberate

**Review by Ralim — CHANGES_REQUESTED** [review]

File: source/Core/Threads/OperatingModes/HomeScreen.cpp (hunk 1 above)
Comment (discip) [reply source/Core/Threads/OperatingModes/HomeScreen.cpp]: Sorry, didn't mean to corrupt anything.

Comment (Ralim) [reply source/Core/Threads/OperatingModes/HomeScreen.cpp]: Your fiine :)

**Review by Ralim — APPROVED** [review]

File: source/Core/Threads/OperatingModes/HomeScreen.cpp (hunk 1 above)
Comment (discip) [reply source/Core/Threads/OperatingModes/HomeScreen.cpp]: > This causes the blink to kick in and out randomly, the 10C gap here is deliberate

Before changing the code I checked if that would work and it worked fine for the **`TS80P`**. 🤷🏻

Comment (Ralim) [reply source/Core/Threads/OperatingModes/HomeScreen.cpp]: It will _work_, but if it's a very slowly cooling down iron (especially with a big tip), it can flicker on and off. This makes it a bit more sticky.

Comment (discip) [reply source/Core/Threads/OperatingModes/HomeScreen.cpp]: Ah, ok!
Thanks for the clarification!
